### ISSUE TITLE
텍스트 스타일링 오류

### ISSUE THREAD

**Issue by mingael** [lovefields/dragonEditor#10]
# 벌레
1. 볼드 + 색상 적용된 글자를 같이 선택했을 때, 색상 있는 글자부터 드래그해서 볼드 설정하면 아무 동작도 일어나지 않음
2. 색상 적용된 글자를 굵게 처리하면 색상이 사라짐
3. ????????? 취소선 적용 안할 글자 + 적용한 글자를 드래그해서 취소선 버튼을 여러번 누르니까 글자 몇개 남기고 에디터 영역(?)이 사라짐
- 사라진 상태: `<div class="editor-content djs-content">ehf</div>`
4. Add text 에도 스타일 적용이 됨
5. 테이블에서 한글 적고서 탭 하면 마지막 입력한 글자를 가져가서 다음 칸에 입력됨

# 요청사항
1. 코드블럭에 스타일 적용 후 코드 작업 시 스타일이 적용될 수 있게 해주세요

**Comment by lovefields** [comment]
dev brnach에 bug 4,5 수정.

**Comment by lovefields** [comment]
1.0.6 에 4,5번 반영
