### ISSUE TITLE
커서 이동 이슈

### ISSUE THREAD

**Issue by mingael** [lovefields/dragonEditor#47]
아무 내용 입력 없이 공백으로만 행을 만들었을 때
```




```
이런 상태일 때 키보드 방향키 위/아래를 눌러 커서 이동을 하면
1, 정상적으로 한 행씩 이동
```

이동 전 위치
이동 후 위치

```
2. 비정상적으로 한 행을 건너뛰고 두 행씩 이동
```

이동 전 위치

이동 후 위치
```
또한 좌/우 방향키로는 대체적으로 행 간 이동이 안되는데, 가끔 이동이 될 때가 있습니다.

**Comment by lovefields** [comment]
엔터를 2번 할 경우 비정상 엘리먼트 사입에 의한 이슈
